# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

SSH_ENV="$HOME/.ssh/environment"

function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    	start_agent;
    }
else
    start_agent;
fi

alias repos='cd /c/Users/sgomena.GLOBAL/Documents/repos'
alias gs='git status'
alias cdl='cd $@ && ls'
alias pythonsqe='C:/Users/sgomena.GLOBAL/Documents/repos/python/Python27/python.exe'
alias python3.6='/c/Users/sgomena.GLOBAL/AppData/Local/Programs/Python/Python36-32/python.exe'
alias reload='cd && source .bashrc && cd -'
alias hw='echo Hello World'

function mkdircd () { mkdir -p "$@" && eval cd "\"\$$#\""; }

