#!/bin/bash

set -exo pipefail

curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
jabba install zulu@1.11.0-10
jabba alias default zulu@1.11.0-10

sudo snap install gradle --classic

USERNAME="$1"
PASSWORD="$2"

response=$(curl -sSL -X POST -u "$USERNAME:$PASSWORD" https://artifactory.company.com/artifactory/api/security/apiKey)
apiKey=$(echo "$response" | jq -r .apiKey)

# This outputs 1 (e.g. echo $? === 1)
if [ "$apiKey" = "null" ]; then
  echo "Couldn't create API key; checking if key already exists"
  error=$(echo "$response" | jq -r .error)
  if [[ $error =~ "key already exists" ]]; then
    echo "API key already exists; fetching"
    apiKey=$(curl -sSL -u "$USERNAME:$PASSWORD" https://artifactory.company.com/artifactory/api/security/apiKey | jq -r .apiKey)
  else
    echo "Couldn't get API key; defaulting to none"
  fi
fi

mkdir -p ~/.gradle
if [ -n "$apiKey" ]; then
  cat << EOF >> ~/.gradle/gradle.properties
# This file was automatically generated by the onboarding toolset
# You should ensure the following values are correct if you run into issues!

artifactoryUser=$USERNAME
artifactoryPass=$apiKey
EOF
else
  cat << EOF >> ~/.gradle/gradle.properties
# This file was automatically generated by the onboarding toolset
# You will need to modify the following values for it to work properly!

artifactoryUser=<username>
# To get an API key, go to https://artifactory.company.com/ui/admin/artifactory/user_profile 
# Click "Unlock" in the User Profile section
# Click "Generate API Key" in the Authentication Settings section
artifactoryPass=<artifactory API key>
EOF
fi